import type { SuiteTool } from '@/lib/types';

/**
 * Real, top-level product URLs -- looked up server-side from this fixed
 * map, never generated by the LLM. Letting a model emit an arbitrary URL
 * that then gets rendered as a clickable link is both a hallucination
 * risk (a plausible-looking but wrong/dead URL) and an injection risk (a
 * crafted response steering a user somewhere unintended); constraining
 * `tool` to this enum and resolving the URL ourselves avoids both.
 */
export const TOOL_INFO: Record<SuiteTool, { label: string; url: string; specialty: string }> = {
  descript: {
    label: 'Descript',
    url: 'https://www.descript.com/',
    specialty: 'audio/transcript repair (Studio Sound, filler-word removal, overdub)',
  },
  opusclip: {
    label: 'OpusClip',
    url: 'https://www.opus.pro/',
    specialty: 'short-form clip slicing from longer footage',
  },
  hyperframes: {
    label: 'HyperFrames by HeyGen',
    url: 'https://www.heygen.com/',
    specialty: 'AI avatar B-roll and programmable video compositions',
  },
  canva: {
    label: 'Canva',
    url: 'https://www.canva.com/',
    specialty: 'thumbnail and cover-image templates',
  },
};
